-- 1. Suppliers Table
-- Stores information about each supplier.
CREATE TABLE suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    contact_person TEXT,
    phone TEXT,
    address TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for suppliers table
ALTER TABLE suppliers ENABLE ROW LEVEL SECURITY;

-- Policy: Authenticated users can manage suppliers
CREATE POLICY "Allow authenticated users to manage suppliers"
ON suppliers
FOR ALL
USING (auth.role() = 'authenticated');


-- 2. Purchases Table
-- Stores a record of each purchase/stock-in event.
CREATE TABLE purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
    purchase_date DATE NOT NULL DEFAULT CURRENT_DATE,
    total_amount NUMERIC(10, 2) DEFAULT 0.00,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for purchases table
ALTER TABLE purchases ENABLE ROW LEVEL SECURITY;

-- Policy: Authenticated users can manage purchases
CREATE POLICY "Allow authenticated users to manage purchases"
ON purchases
FOR ALL
USING (auth.role() = 'authenticated');


-- 3. Purchase Items Table
-- Stores the individual items within each purchase.
-- We assume you have a 'products' table. Update 'product_id' reference if your table is named differently.
CREATE TABLE purchase_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_id BIGINT NOT NULL REFERENCES purchases(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id), -- IMPORTANT: Change 'products(id)' if your products table has a different name
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    purchase_price NUMERIC(10, 2) NOT NULL CHECK (purchase_price >= 0),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for purchase_items table
ALTER TABLE purchase_items ENABLE ROW LEVEL SECURITY;

-- Policy: Authenticated users can manage purchase items
CREATE POLICY "Allow authenticated users to manage purchase_items"
ON purchase_items
FOR ALL
USING (auth.role() = 'authenticated');