-- Create the inventory table to store individual stock items
CREATE TABLE public.inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
    imei TEXT UNIQUE,
    color TEXT,
    condition TEXT,
    purchase_price NUMERIC,
    sale_price NUMERIC,
    status TEXT DEFAULT 'Available' NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Add a comment to explain the purpose of the table
COMMENT ON TABLE public.inventory IS 'Stores individual stock items, linking them to a master product.';