-- 1. Supplier Refunds ka Table banayein
CREATE TABLE public.supplier_refunds (
  id bigint generated by default as identity not null,
  supplier_id bigint not null,
  amount numeric not null,
  refund_date date not null default current_date,
  payment_method text null, -- Cash, Bank Transfer etc.
  notes text null,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null default auth.uid(),
  
  constraint supplier_refunds_pkey primary key (id),
  constraint supplier_refunds_supplier_id_fkey foreign key (supplier_id) references suppliers (id) on delete cascade,
  constraint supplier_refunds_user_id_fkey foreign key (user_id) references auth.users (id)
) TABLESPACE pg_default;

-- 2. RPC Function banayein (Jo Refund save karega aur Credit kam karega)
CREATE OR REPLACE FUNCTION record_supplier_refund(
  p_supplier_id bigint,
  p_amount numeric,
  p_refund_date date,
  p_method text,
  p_notes text
) RETURNS void AS $$
BEGIN
  -- A. Refund ka record save karein
  INSERT INTO supplier_refunds (supplier_id, amount, refund_date, payment_method, notes)
  VALUES (p_supplier_id, p_amount, p_refund_date, p_method, p_notes);

  -- B. Supplier ka Credit Balance kam karein (Minus)
  UPDATE suppliers
  SET credit_balance = credit_balance - p_amount
  WHERE id = p_supplier_id;
END;
$$ LANGUAGE plpgsql;