-- Table: payment_allocations
-- Maqsad: Yeh yaad rakhna ke Payment ka konsa hissa kis Purchase ke liye use hua.

CREATE TABLE public.payment_allocations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id bigint NOT NULL REFERENCES public.supplier_payments(id) ON DELETE CASCADE,
    purchase_id bigint NOT NULL REFERENCES public.purchases(id) ON DELETE CASCADE,
    amount numeric NOT NULL CHECK (amount > 0),
    created_at timestamp with time zone DEFAULT now()
);

-- Performance ke liye Index (Taake search tez ho)
CREATE INDEX idx_payment_allocations_payment_id ON public.payment_allocations(payment_id);
CREATE INDEX idx_payment_allocations_purchase_id ON public.payment_allocations(purchase_id);