-- Devices ko track karne ke liye table
create table if not exists public.device_registry (
    id bigint generated by default as identity primary key,
    device_info text,
    user_id uuid references auth.users(id) default auth.uid(),
    created_at timestamp with time zone default now()
);

-- RLS (Security) On karein
alter table public.device_registry enable row level security;

-- Policies banayein (Sirf logged in users naya device register kar sakein)
create policy "Enable insert for authenticated users only"
on public.device_registry
for insert
to authenticated
with check (true);

create policy "Enable select for authenticated users only"
on public.device_registry
for select
to authenticated
using (true);